### ISSUE TITLE
What is the license of dsl4xml?

### ISSUE THREAD

**Issue by ghost** [steveliles/dsl4xml#5]
Some information about the license would be appreciated.

**Comment by steveliles** [comment]
what license would you like? Apache 2?

**Comment by kidahl73** [comment]
I consider using it in an Android app that needs modifications that would be uninteresting to most users and probably break backwards compatibility. A BSD/Public Domain licence would be the simplest.

**Comment by steveliles** [comment]
BSD licensed d543adac36c147c1ab9ef508425a70b3a2105555
